# -*- coding: utf-8 -*-
"""Binance_Klines_Agent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iVRm_Ne9aJTrd641MbTbG7UeELbZDKV-

# Binance Historical Klines Agent (LangGraph + LangChain)

## Scenario

**Domain:** downloading and organizing historical cryptocurrency market data from Binance's public archive — [data.binance.vision](https://data.binance.vision/).

Binance publishes daily and monthly ZIP archives of historical "candles" (klines) for traded pairs (symbols) and different intervals such as `1m`, `5m`, `1h`, and `1d`. Turning these archives into data that can be used for analysis requires several steps: (1) understand exactly what the user wants (symbol, candle interval, date range), (2) validate the requested symbol, (3) determine which Binance archive files are required, (4) download and unzip the archives, (5) recognize and parse the CSV format, including timestamp units, and (6) organize the downloaded data into pandas DataFrames.

This notebook builds a **two-agent LangGraph workflow** that automates this process:

1. **Planner Agent** — parses the natural-language request, determines the requested symbol, candle interval, archive period type, and date range, validates the symbol using the `validate_symbol` tool, and produces a structured `DownloadPlan`.

2. **Human-in-the-loop Review** — BEFORE any data is downloaded, the graph pauses and presents the generated plan to a human for approval. The review includes the symbol, interval, date range, and files that will be downloaded. The human can either approve the plan or provide feedback requesting a change. When the plan is rejected, the workflow loops back to the Planner Agent with the reviewer's feedback.

3. **Downloader Agent** — only after human approval, the Downloader Agent processes the approved list of archive periods. It uses the `fetch_and_store_candles` tool to download each Binance archive, unzip the CSV file, detect the timestamp format, parse the data, and store the resulting pandas DataFrame in memory. A safety parameter, `max_files`, limits the number of archives that can be downloaded in a single run.

4. **Pandas DataFrames** — the downloaded data is kept as pandas DataFrames in Python memory. Each downloaded archive is stored separately and can then be combined into a single DataFrame for analysis.

5. **Report** — after downloading is complete, the workflow produces a Markdown report containing the approved plan, downloaded periods, status of each archive, row counts, and totals.

The workflow therefore follows this architecture:

```text
User request
     │
     ▼
┌──────────────────┐
│  Planner Agent   │
│                  │
│ validate_symbol  │
└────────┬─────────┘
         │
         ▼
   DownloadPlan
         │
         ▼
┌──────────────────┐
│   Human Review   │
└───────┬────┬─────┘
        │    │
   revise    │ approve
        │    │
        │    ▼
        │ ┌────────────────────┐
        │ │  Downloader Agent  │
        │ │                    │
        │ │ fetch_and_store_   │
        │ │     candles        │
        │ └─────────┬──────────┘
        │           │
        │           ▼
        │    pandas DataFrames
        │           │
        └───────────┘
                    │
                    ▼
                  Report
```

The workflow does **not** use SQLite or SQL. The downloaded market data is represented directly as pandas DataFrames, which keeps the implementation focused on the agent workflow and data-processing steps.

### Assignment compliance

| Requirement                                             | Where it's satisfied                                             |
| ------------------------------------------------------- | ---------------------------------------------------------------- |
| Scenario defined in a Markdown cell                     | The cell above                                                   |
| >=2 distinct agents, each with a role/system prompt     | `planner_agent`, `downloader_agent`                              |
| Defined state (`TypedDict`)                             | `SystemState`                                                    |
| >=2 different tools, actually used                      | `validate_symbol`, `fetch_and_store_candles`                      |
| Conversational/workflow memory                          | `MemorySaver` checkpointer + `messages` state key                |
| Human-in-the-loop interruption before a critical action | `interrupt()` in `human_review`, before the actual data download |
| `execute_workflow(user_request)` core function          | Defined below; handles graph execution and interrupt/resume      |
| >=5 test cases, showing approve and revise              | Test Cases section                                               |
| No hardcoded API keys                                   | Environment variables / Colab Secrets                            |
| Data processing with pandas                             | Downloaded archives are parsed into pandas DataFrames            |
| No SQL/database dependency                              | Data is stored in Python memory as pandas DataFrames             |
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install -q langgraph langchain langchain-openai langchain-community

import os
import re
import io
import json
import zipfile
from pathlib import Path
import sqlite3
import uuid
from datetime import date, datetime, timedelta
from typing import TypedDict, Annotated, Optional, Literal

import requests
import pandas as pd

from pydantic import BaseModel, Field

from langchain.agents import create_agent
from langchain_openai import ChatOpenAI

from langchain_core.tools import tool
from langchain_core.messages import HumanMessage, AIMessage, SystemMessage, ToolMessage


from langgraph.graph import StateGraph, END, START
from langgraph.graph.message import add_messages
from langgraph.checkpoint.memory import MemorySaver
from langgraph.types import interrupt, Command

from dotenv import load_dotenv

from langchain_work.utils import display_graph

dotenv_path = Path(r'../env/.env.prod')
load_dotenv(dotenv_path=dotenv_path)

os.environ["LANGSMITH_PROJECT"] = "Exchange_Assistant"
openai_api_key = os.environ.get("OPENAI_API_KEY")

class ExchangeState(BaseModel):
    name: str
    url: str
    symbols: list[str]
    intervals: list[str]
    columns: list[str]
    period_types: list[str]
    notes: str | None = None


class DownloadPlan(BaseModel):
    symbol: str = Field(description="Trading pair, e.g. BTCUSDC")

    interval: str = Field(description="Candle interval, e.g. 1m, 1h, 1d")

    period_type: Literal["daily", "monthly"] = Field(description="'daily' for day-level archives, 'monthly' for whole-month archives")

    start_date: str = Field(description="Start of range: YYYY-MM-DD for daily, YYYY-MM for monthly")

    end_date: str = Field(description="End of range (inclusive): YYYY-MM-DD for daily, YYYY-MM for monthly")

    reasoning: str = Field(description="Brief note on how these parameters were derived, and any concerns")


class SystemState(TypedDict):
    user_request: str
    exchange: ExchangeState

    plan: DownloadPlan | None
    human_decision: dict
    feedback_history: list[str]
    download_summary: dict | None
    draft_report: str

    autopilot: bool
    max_files: int
    messages: Annotated[list, add_messages]
    downloaded_data: dict

@tool
def validate_symbol(symbol: str) -> str:

    """
    Validate a Binance Spot trading pair.
    Checks via the public Binance REST API whether the symbol actually exists, before we plan to download data for it.
    """
    #TODO need to update validate_symbol to be used with different exchange not only Binance

    symbol = symbol.upper().strip()

    try:
        response = requests.get(
            "https://api.binance.com/api/v3/exchangeInfo",
            params={"symbol": symbol},
            timeout=10,
        )

        if response.status_code == 200:
            data = response.json()
            valid = bool(data.get("symbols"))

            return json.dumps({
                "symbol": symbol,
                "valid": valid,
                "status": ("found" if valid else "not_found"),
            })

        if response.status_code == 451:

            return json.dumps({
                "symbol": symbol,
                "valid": None,
                "status": "unavailable",
                "reason": (
                    "Binance returned HTTP 451. "
                    "Symbol validity could not be confirmed."
                ),
            })

        return json.dumps({
            "symbol": symbol,
            "valid": None,
            "status": f"http_{response.status_code}",
        })

    except Exception as e:

        return json.dumps({
            "symbol": symbol,
            "valid": None,
            "status": "error",
            "reason": str(e)[:100],
        })



@tool
def fetch_and_store_candles(symbol: str, interval: str, period_type: str, period_label: str) -> str:

    """
    Download one Binance historical candle archive and store the resulting pandas DataFrame in memory.
    """

    try:
        df, summary = download_binance_candles(symbol=symbol, interval=interval, period_type=period_type, period_label=period_label)

        if df is None:
            return json.dumps(summary)

        key = (f"{symbol}_{interval}_{period_label}")
        downloaded_data[key] = df

        return json.dumps({
            **summary,
            "data_key": key,
            "columns": list(df.columns),
        })

    except Exception as e:
        return json.dumps({
            "symbol": symbol,
            "interval": interval,
            "period_type": period_type,
            "period_label": period_label,
            "status": "error",
            "error": str(e),
        })

PLANNER_SYSTEM_PROMPT = """
You are the Planner Agent.
Your role is to analyze the user's historical cryptocurrency data request and create a DownloadPlan.

The available exchange is Binance.

IMPORTANT RULES:

1. You MUST use the validate_symbol tool to validate the requested trading pair.

2. If validate_symbol returns valid=true:
   the symbol is confirmed.

3. If validate_symbol returns valid=false:
   the symbol is invalid.
   Do not substitute another symbol. Explain the problem in reasoning.

4. If validation cannot be completed because of an API error, HTTP 451, timeout, or another unavailable response:
   do NOT treat the symbol as invalid.
   Explain that validation could not be completed.

5. Determine the appropriate interval from the user request.

6. Determine the appropriate archive period type.

7. Keep the requested date range.

8. Do not invent dates.

9. Do not download anything.

10. Return a structured DownloadPlan.

The human reviewer will approve or revise your plan
before any data is downloaded.
"""

"""## Agent 1 -- Planner

**Role:** turns the natural-language request into a structured `DownloadPlan`. Uses
`validate_symbol` to check the symbol is real before finalizing the plan. If there's feedback
from an earlier review round, it's folded into the new plan.
"""

def planner(state: SystemState) -> dict:

    user_request = state.get("user_request")

    if not user_request:
        return {"plan": None, "messages": []}

    today_iso = date.today().isoformat()
    exchange = state["exchange"]
    feedback_history = state.get("feedback_history", [])

    planner_prompt = f"""
You are the Planner Agent.

Your role is to create a DownloadPlan for downloading
historical cryptocurrency data from Binance.

Today's date is {today_iso}.

Available exchange:{exchange.name}

Supported symbols:{exchange.symbols}

Supported intervals:{exchange.intervals}

Supported archive period types:{exchange.period_types}

Exchange notes:{exchange.notes or "None"}

IMPORTANT RULES:

1. You MUST use the validate_symbol tool to validate
   the requested trading pair.

2. The original user request is:{user_request}

3. If there is human reviewer feedback from a previous
   planning attempt, that feedback MUST be applied to
   the new plan.

4. Human reviewer feedback has priority over the
   corresponding part of the original user request.

5. For example, if the original request says:

   "Download BTCUSDC 1h data..."

   and the human says:

   "Please use ETHUSDC instead of BTCUSDC."

   then the NEW plan MUST use:

   symbol = ETHUSDC

6. Do not keep the old value when the human explicitly
   asks you to change it.

7. Do not silently change values that the human did not
   ask to change.

8. If the reviewer changes the symbol, validate the NEW
   symbol using validate_symbol.

9. If the reviewer changes the interval, use the NEW
   interval.

10. If the reviewer changes the date range, use the NEW
    date range.

11. Do not download any data. Your job is only to create
    the plan.

12. Return a structured DownloadPlan.
"""

    if feedback_history:

        planner_prompt += """

HUMAN REVIEWER FEEDBACK:
The previous plan was rejected.
The following feedback MUST be applied to the new plan:

"""

        planner_prompt += "\n".join(f"- {feedback}" for feedback in feedback_history)

    # Create a fresh planner agent with
    # the dynamic exchange/feedback prompt.

    planner_agent = create_agent(
        model=ChatOpenAI(
            model="gpt-5.6-luna",
            api_key=openai_api_key,
            reasoning_effort="none",
        ),
        tools=[validate_symbol],
        system_prompt=planner_prompt,
        response_format=DownloadPlan,
    )

    planner_result = planner_agent.invoke(
        input={"messages": [HumanMessage(content=user_request)]}
        )

    return {
        "plan": planner_result["structured_response"],
        "messages": planner_result["messages"],
    }



"""## Agent 2 -- Downloader

**Role:** downloads and stores the data -- but only AFTER the plan is approved.
`compute_period_labels` deterministically computes the exact list of dates/months in plain
Python (rather than relying on the LLM to count dates correctly), and is capped by `max_files`
-- a safety parameter controlled by `execute_workflow`, NOT by the LLM. The Downloader agent gets
that exact list and calls `fetch_and_store_candles` once per item -- genuine tool-calling (ReAct)
behavior, but with a deterministically computed and bounded scope. The final report is built by
Python directly from the tool results (not from the LLM's free text), so the numbers are
guaranteed accurate.
"""

downloaded_data: dict[str, pd.DataFrame] = {}


def compute_period_labels(period_type: str, start_date: str, end_date: str, max_files: int) -> list[str]:

    labels = []

    if period_type == "daily":
        current = date.fromisoformat(start_date)
        end = date.fromisoformat(end_date)

        while (current <= end and len(labels) < max_files):
            labels.append(current.isoformat())
            current += timedelta(days=1)

    elif period_type == "monthly":
        year, month = (int(x) for x in start_date.split("-"))
        end_year, end_month = (int(x) for x in end_date.split("-"))

        while (year < end_year or (year == end_year and month <= end_month)) and len(labels) < max_files:
            labels.append(f"{year:04d}-{month:02d}")
            month += 1

            if month > 12:
                month = 1
                year += 1

    else:
        raise ValueError(f"Unsupported period_type: {period_type}")

    return labels

def download_binance_candles(symbol: str, interval: str, period_type: str, period_label: str):

    base_url = ("https://data.binance.vision/data")
    url = (f"{base_url}/spot/{period_type}/klines/{symbol}/{interval}/{symbol}-{interval}-{period_label}.zip")

    response = requests.get(url, timeout=60)

    if response.status_code == 404:

        return None, {
            "symbol": symbol,
            "interval": interval,
            "period_type": period_type,
            "period_label": period_label,
            "status": "not_found",
            "rows": 0,
        }

    response.raise_for_status()

    with zipfile.ZipFile(io.BytesIO(response.content)) as archive:

        csv_files = [name for name in archive.namelist() if name.endswith(".csv")]

        if not csv_files:
            raise ValueError("No CSV file found in archive.")

        csv_name = csv_files[0]

        with archive.open(csv_name) as csv_file:
            df = pd.read_csv(csv_file,header=None)

    # Binance historical cadle columns
    column_names = [ "open_time", "open", "high", "low", "close", "volume", "close_time", "quote_asset_volume", "number_of_trades", "taker_buy_base_volume", "taker_buy_quote_volume", "ignore" ]

    df.columns = column_names[:len(df.columns)]

    # Convert timestamp
    if not df.empty:
        if df["open_time"].max() > 10**14:
            df["open_time"] = pd.to_datetime(df["open_time"], unit="us", utc=True)
        else:
            df["open_time"] = pd.to_datetime(df["open_time"], unit="ms", utc=True)

    return df, {
        "symbol": symbol,
        "interval": interval,
        "period_type": period_type,
        "period_label": period_label,
        "status": "ok",
        "rows": len(df),
    }

def downloader_system_prompt(labels: list[str], plan: dict) -> str:

    return f"""
You are the Downloader Agent.

The human reviewer has APPROVED the following plan.

Symbol:
{plan["symbol"]}

Interval:
{plan["interval"]}

Period type:
{plan["period_type"]}

Start date:
{plan["start_date"]}

End date:
{plan["end_date"]}

You have been given this EXACT list of period labels:

{labels}

Your task is to download every requested period.

For EACH label:

- Call fetch_and_store_candles exactly once.
- Use the approved symbol.
- Use the approved interval.
- Use the approved period type.
- Use the current period label.

Rules:

- Do not invent labels.
- Do not skip labels.
- Do not download anything outside the list.
- Do not change the approved plan.
- Do not call the tool twice for the same label.

After all labels have been processed:

- Give a short summary.
- Report only information returned by the tool.
- Do not invent row counts.
"""

def downloader_agent(state: SystemState) -> dict:

    """
      Downloads and stores the data but only AFTER the plan is approved.
    """

    plan = state["plan"]

    if plan is None:
        raise ValueError("No approved download plan.")

    plan_dict = plan.model_dump()

    max_files = state.get("max_files", 5)

    labels = compute_period_labels(
        period_type=plan.period_type,
        start_date=plan.start_date,
        end_date=plan.end_date,
        max_files=max_files,
    )

    download_agent = create_agent(
        model=ChatOpenAI(
            model="gpt-5.6-luna",
            api_key=openai_api_key,
            reasoning_effort="none",
        ),
        tools=[fetch_and_store_candles],
        system_prompt=downloader_system_prompt(labels=labels, plan=plan_dict),
    )

    result = download_agent.invoke(
        input={
            "messages": [HumanMessage(content=("Execute the approved download plan for these labels: {labels}"))]
        }
    )

    messages = result["messages"]
    fetch_results = []

    for message in messages:

        if isinstance(message, ToolMessage):
            try:
                tool_result = json.loads(message.content)
                fetch_results.append(tool_result)

            except Exception:
                pass

    total_rows = sum(item.get("rows", 0) for item in fetch_results)

    files_ok = sum(1 for item in fetch_results if item.get("status") == "ok")

    files_missing = sum(1 for item in fetch_results if item.get("status") == "not_found")

    files_error = sum(1 for item in fetch_results if item.get("status") == "error")

    return {
        "download_summary": {
            "plan": plan_dict,
            "labels_requested": labels,
            "fetch_results": fetch_results,
            "total_rows": total_rows,
            "files_ok": files_ok,
            "files_missing": files_missing,
            "files_error": files_error,
        },
        "messages": messages,
    }

"""## Human-in-the-Loop Review

The review happens BEFORE the Downloader -- it approves the plan (symbol, interval, date range,
number of files), not the final report.
"""

def human_review(state: SystemState) -> dict:

    if state.get("autopilot"):
        return {
            "human_decision": {"approved": True, "feedback": ""}
            }

    plan = state["plan"]

    if plan is None:
        raise ValueError("No download plan available.")

    max_files = state.get("max_files",5)

    labels = compute_period_labels(
        period_type=plan.period_type,
        start_date=plan.start_date,
        end_date=plan.end_date,
        max_files=max_files,
    )

    decision = interrupt({
        "question": ("Approve this download plan? Reply with approved=True,or approved=False plus feedback."),
        "plan": plan.model_dump(),
        "files_to_download": labels,
        "file_count": len(labels),
    })

    return {"human_decision": decision}


def route_after_review(state: SystemState) -> str:

    decision = state.get("human_decision", {})

    if decision.get("approved"):
        return "downloader"

    return "apply_feedback"


def merge_feedback(state: SystemState) -> dict:

    decision = state.get("human_decision", {})

    feedback = decision.get("feedback", "").strip()

    history = list(state.get("feedback_history", []))

    if feedback:
        history.append(feedback)

    return {"feedback_history": history}

def report_node(state: SystemState) -> dict:

    summary = state["download_summary"]
    plan = summary["plan"]
    lines = [
        "### Download report", "",
      f"**Symbol:** {plan['symbol']} | **Interval:** {plan['interval']} | **Period type:** {plan['period_type']}",
      f"**Range:** {plan['start_date']} → {plan['end_date']}",
        "",
        "| Period | Status | Rows |",
        "|---|---|---:|",
    ]

    for result in summary["fetch_results"]:
        lines.append(f"| {result.get('period_label', '')} | {result.get('status', '')} | {result.get('rows', 0)} |")

    lines.extend(["",
                  f"**Total rows:** {summary['total_rows']}",
                  f"**Files OK:** {summary['files_ok']}  | **Missing:** {summary['files_missing']}  | **Errors:** {summary['files_error']}"
     ])

    draft_report = "\n".join(lines)

    return {
        "draft_report": draft_report,
        "messages": [AIMessage(content=draft_report)],
    }

"""## Building the LangGraph

Flow: `planner -> human_review -> (downloader -> report -> END) | (apply_feedback -> planner)`,
looping until the plan is approved. `MemorySaver` keeps state keyed by `thread_id`, which is what
makes the interrupt/resume mechanism possible.
"""

graph_builder = StateGraph(SystemState)
graph_builder.add_node("planner", planner)
graph_builder.add_node("human_review", human_review)
graph_builder.add_node("apply_feedback", merge_feedback)
graph_builder.add_node("downloader", downloader_agent)
graph_builder.add_node("report", report_node)

graph_builder.add_edge(START, "planner")
graph_builder.add_edge("planner", "human_review")
graph_builder.add_conditional_edges(
    "human_review",
    route_after_review,
    {"downloader": "downloader", "apply_feedback": "apply_feedback"})
graph_builder.add_edge("apply_feedback", "planner")
graph_builder.add_edge("downloader", "report")
graph_builder.add_edge("report", END)

checkpointer = MemorySaver()
graph = graph_builder.compile(checkpointer=checkpointer, debug=True)

display_graph(graph, Path("./graph.png"))

binance = ExchangeState(
    name="BINANCE",
    url="https://data.binance.vision/?prefix=data/spot/",
    symbols=["BTCUSDC", "ETHUSDC", "SOLUSDC"],
    intervals=["1m", "15m", "30m", "1h", "2h", "4h", "12h", "1d"],
    columns=["open_time", "open", "high", "low", "close", "volume"],
    period_types=["daily", "monthly"],
    notes="Daily archives are usually published on the following UTC day."
)

"""

**********************************************************

## TEST 1 when approve plan

**********************************************************"""

thread1_config = {"configurable": {"thread_id": "thread1-test-1"}}

graph.invoke(
    input={
        "user_request": ("Download BTCUSDC 1h data from 2026-01-01 to 2026-01-10"),
        "exchange": binance,
        "feedback_history": [],
        "autopilot": False,
        "max_files": 5,
    },
    config=thread1_config,
)

test_result_1 = graph.invoke(
    input=Command(
        resume={
            "approved": True,
            "feedback": "",
        }
    ),
    config=thread1_config,
)

print(test_result_1["draft_report"])


final_df = pd.concat(
    downloaded_data.values(),
    ignore_index=True,
)

display_graph(final_df, Path("./final_df.png"))

"""
**********************************************************

## TEST 2 when approve plan

**********************************************************"""

downloaded_data.clear()
thread1_config = {"configurable": {"thread_id": "thread1-test-2"}}

graph.invoke(
    input={
        "user_request": ("Download BTCUSDC 1h data from 2026-01-01 to 2026-01-10"),
        "exchange": binance,
        "feedback_history": [],
        "autopilot": False,
        "max_files": 5,
    },
    config=thread1_config,
)

test_result_2 = graph.invoke(
    input=Command(
        resume={
            "approved": False,
            "feedback": "Please use ETHUSDC instead of BTCUSDC.",
        }
    ),
    config=thread1_config,
)

test_result_2_1 = graph.invoke(
    input=Command(
        resume={
            "approved": True,
            "feedback": "",
        }
    ),
    config=thread1_config,
)

print(test_result_2_1["draft_report"])

final_df = pd.concat(
    downloaded_data.values(),
    ignore_index=True,
)
display_graph(final_df, Path("./final_df.png"))

"""**********************************************************

## TEST 3 when approve plan

**********************************************************
"""

downloaded_data.clear()
thread1_config = {"configurable": {"thread_id": "thread1-test-3"}}

graph.invoke(
    input={
        "user_request": ("Download BTCUSDC 1h data from 2026-01-01 to 2026-01-10"),
        "exchange": binance,
        "feedback_history": [],
        "autopilot": False,
        "max_files": 5,
    },
    config=thread1_config,
)

result_3 = graph.invoke(
    input=Command(
        resume={
            "approved": False,
            "feedback": "Please change the interval from 1h to 4h.",
        }
    ),
    config=thread1_config,
)

test_result_3_1= graph.invoke(
    input=Command(
        resume={
            "approved": True,
            "feedback": "",
        }
    ),
    config=thread1_config,
)

print(test_result_3_1["draft_report"])

final_df = pd.concat(
    downloaded_data.values(),
    ignore_index=True,
)
display_graph(final_df, Path("./final_df.png"))

"""**********************************************************

## TEST 4 when approve plan

**********************************************************
"""

downloaded_data.clear()
thread1_config = {"configurable": {"thread_id": "thread1-test-4"}}

graph.invoke(
    input={
        "user_request": ("Download BTCUSDC 1h data from 2026-01-01 to 2026-01-10"),
        "exchange": binance,
        "feedback_history": [],
        "autopilot": False,
        "max_files": 5,
    },
    config=thread1_config,
)

result_4 = graph.invoke(
    input=Command(
        resume={
            "approved": False,
            "feedback": "Please change the date range to 2026-01-01 through 2026-01-05.",
        }
    ),
    config=thread1_config,
)

test_result_4_1 = graph.invoke(
    input=Command(
        resume={
            "approved": True,
            "feedback": "",
        }
    ),
    config=thread1_config,
)

print(test_result_4_1["draft_report"])

final_df = pd.concat(
    downloaded_data.values(),
    ignore_index=True,
)
display_graph(final_df, Path("./final_df.png"))

"""**********************************************************

## TEST 5 when approve plan

**********************************************************
"""

downloaded_data.clear()
thread1_config = {"configurable": {"thread_id": "thread1-test-5"}}

graph.invoke(
    input={
        "user_request": ("Download BTCUSDC 1h daily data from 2026-01-01 to 2026-03-31"),
        "exchange": binance,
        "feedback_history": [],
        "autopilot": False,
        "max_files": 3,
    },
    config=thread1_config,
)

test_result_5 = graph.invoke(
    input=Command(
        resume={
            "approved": False,
            "feedback": (
                "I changed my mind. Please use SOLUSDC "
                "with 1d candles and monthly data instead."
            ),
        }
    ),
    config=thread1_config,
)

print(test_result_5["__interrupt__"][0].value["plan"])

test_result_5_1 = graph.invoke(
    input=Command(
        resume={
            "approved": True,
            "feedback": "",
        }
    ),
    config=thread1_config,
)

print(test_result_5_1["draft_report"])

final_df = pd.concat(
    downloaded_data.values(),
    ignore_index=True,
)
display_graph(final_df, Path("./final_df.png"))

print(final_df.head())
print(final_df.shape)

"""## Core Function: `execute_workflow`

Accepts `user_request` (natural language), starts a new thread, and drives the graph through any
number of interrupt/resume cycles. `simulated_responses` is a queue of simulated human decisions
(used by the test cases below); if omitted, it falls back to real `input()`.
"""

def execute_workflow(
    user_request: str,
    simulated_responses: Optional[list[dict]] = None,
    autopilot: bool = False,
    max_files: int = 5,
    verbose: bool = True,
) -> dict:
    """Run one planner -> human-review -> downloader -> report cycle for `user_request`.

    Args:
        user_request: what to fetch, e.g. "daily 1d candles for BTCUSDT, last 5 days".
        simulated_responses: queue of {"approved": bool, "feedback": str} dicts, consumed in
            order each time the graph interrupts. Ignored entirely when autopilot=True.
        autopilot: if True, the human_review node auto-approves the first plan without pausing --
            useful for unattended/batch runs.
        max_files: safety cap on how many archives can be downloaded in one run. Controlled here,
            not by the LLM, regardless of how large a range the user asked for.
        verbose: print progress as the workflow runs.

    Returns:
        The final graph state, including the approved draft_report and download_summary.
    """
    thread_id = str(uuid.uuid4())
    config = {"configurable": {"thread_id": thread_id}}

    initial_state: SystemState = {
        "user_request": user_request,
        "plan": None,
        "human_decision": {},
        "feedback_history": [],
        "download_summary": None,
        "draft_report": "",
        "autopilot": autopilot,
        "max_files": max_files,
        "messages": [HumanMessage(content=user_request)],
    }

    queue = list(simulated_responses) if simulated_responses is not None else None

    if verbose:
        mode = "AUTOPILOT" if autopilot else "INTERACTIVE"
        print(f"=== Starting workflow (thread {thread_id[:8]}, mode={mode}, max_files={max_files}) ===")
        print(f"Request: {user_request}\n")

    result = graph.invoke(initial_state, config=config)

    round_num = 1
    while "__interrupt__" in result:
        payload = result["__interrupt__"][0].value
        if verbose:
            print(f"--- HUMAN REVIEW (round {round_num}) ---")
            print(json.dumps(payload, indent=2, ensure_ascii=False))
            print()

        if queue:
            human_response = queue.pop(0)
        else:
            approved_raw = input("Approve this plan? (y/n): ").strip().lower()
            approved = approved_raw == "y"
            feedback = "" if approved else input("What should change? ")
            human_response = {"approved": approved, "feedback": feedback}

        if verbose:
            verdict = "APPROVED" if human_response.get("approved") else "REVISION REQUESTED"
            print(f">>> Human decision: {verdict}"
                  + (f" -- '{human_response.get('feedback')}'" if not human_response.get("approved") else ""))
            print()

        result = graph.invoke(Command(resume=human_response), config=config)
        round_num += 1

    if verbose:
        print("=== Final Report ===")
        print(result["draft_report"])

    return result

"""## Test Cases

Six requests, covering: **immediately approved plan**, **review with 1 and 2 revision rounds**,
**autopilot** (no pause at all), and a **tool-driven revision** (the Planner flags an invalid
symbol via `validate_symbol`, and the human corrects it during review).
"""

# Test Case 1 -- approved immediately
result_1_ = execute_workflow(
    "Download daily (1d) candles for BTCUSDT for the last 5 days.",
    simulated_responses=[{"approved": True}],
)

# Test Case 2 -- one revision (shorter range), then approved
result_2_ = execute_workflow(
    "I want monthly (1mo) data for ETHUSDT from January to June 2024.",
    simulated_responses=[
        {"approved": False, "feedback": "That's too many months -- narrow it to January-March 2024."},
        {"approved": True},
    ],
)

# Test Case 3 -- two revisions (interval change, then range change), then approved
result_3_ = execute_workflow(
    "Give me 1h candles for SOLUSDT for the last 4 days.",
    simulated_responses=[
        {"approved": False, "feedback": "Switch the interval to 15m instead of 1h."},
        {"approved": False, "feedback": "Actually, narrow the range to the last 2 days."},
        {"approved": True},
    ],
)

# Test Case 4 -- approved immediately, a differently-phrased request
result_4_ = execute_workflow(
    "Daily klines for BNBUSDT for the last 3 days please.",
    simulated_responses=[{"approved": True}],
)

# Test Case 5 -- invalid symbol caught by the validate_symbol tool; the human corrects it at review
result_5_ = execute_workflow(
    "Download 1d data for FAKEXYZUSDT for the last 3 days.",
    simulated_responses=[
        {"approved": False, "feedback": "FAKEXYZUSDT doesn't exist -- I meant DOGEUSDT instead."},
        {"approved": True},
    ],
)

# Test Case 6 -- AUTOPILOT: no pause at all, for unattended/batch execution
result_6_ = execute_workflow(
    "Automatically download daily (1d) data for ADAUSDT for the last 3 days.",
    autopilot=True,
    max_files=3,
)